# Generated by Django 6.0.6 on 2026-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=500)),
                ('pickup_location', models.CharField(max_length=500)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('current_cycle_hours', models.FloatField(default=0)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
